### ISSUE TITLE
Add production Dockerfile/.dockerignore

### ISSUE THREAD

**Issue by russleyshaw** [siggame/discordbot#2]
Dockerfile should run during image build:
- [ ] Setup project `npm run setup`

Dockerfile should run when new container created
- [ ] Run production environment `npm run start`

.dockerignore should ignore:
- [x] `docs/`
- [x] `.git/`
- [x] `.gitignore`
- [x] `Dockerfile`
- [x] `.dockerignore`

**Comment by LoneGalaxy** [comment]
Not sure if this is right but this is what I did:
```FROM node:latest
LABEL maintainer "siggame@mst.edu"

ADD . discordbot
WORKDIR discordbot

RUN npm run setup
RUN npm run start

CMD ["npm", "run"]

**Comment by LoneGalaxy** [comment]
Also this is what I did for .dockerignore
```# Files
Dockerfile/
docs/

# Git
.git/
.gitignore
.dockerignore
