### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by russleyshaw** [siggame/discordbot#3]
`package.json` should include scripts to:
- [x] Setup project (install dependencies) `npm run setup`
- [x] Start service `npm run start` `node app.js`
- [x] Start production service `npm run start-prod` `NODE_ENV=production node app.js`

**Comment by russleyshaw** [comment]
For help, take a look at siggame/colisee-* repos

**Comment by LoneGalaxy** [comment]
This should be done, please let me know if anything is out of order. *thumbs up*
