### ISSUE TITLE
Enable automated build on Dockerhub

### ISSUE THREAD

**Issue by russleyshaw** [siggame/discordbot#4]
We have a `Dockerfile` that describes how our code should be built and run. 
We can build a Docker Image using the `Dockerfile`. The Docker Image allows us to run the code in a Docker Container.
A Docker Container is almost like a mini-virtual computer.
[DockerHub](https://hub.docker.com) can integrate with GitHub to build and host the Docker images.
When creating a DockerHub automated build, if commits are pushed to the repo, Docker will try to update the images. 

1. Sign into DockerHub
![image](https://cloud.githubusercontent.com/assets/2314816/25093331/7318891e-2357-11e7-8cd7-33bbbf0080ff.png)

2. Select `Create` from top navigation bar
3. Select `Create Automated Build` from drop-down
![image](https://cloud.githubusercontent.com/assets/2314816/25093337/7bd184d4-2357-11e7-85d2-7db36b17c6f0.png)

4. Select `Create Auto-Build GitHub`
![image](https://cloud.githubusercontent.com/assets/2314816/25093344/8459e38a-2357-11e7-92d4-55bde28d7659.png)

5. Select `siggame` on left, `discordbot` on right.
![image](https://cloud.githubusercontent.com/assets/2314816/25093359/9223029e-2357-11e7-91a2-6874f234bb1b.png)

6. Select `siggame` as Repository namespace
![image](https://cloud.githubusercontent.com/assets/2314816/25093384/adc1535c-2357-11e7-87bb-8faded720ae6.png)

7. Click `Create`

**Comment by LoneGalaxy** [comment]
Done
