### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by russleyshaw** [siggame/discordbot#5]
Ignore dev environments:
- [x] `vagrant/`
- [x] `.idea/`
- [x] `.vscode/`
- [x] `*.log`

- [x] `.env` - this file could include envirnoment variables and sensitive info

**Comment by LoneGalaxy** [comment]
Created a .gitignore file and added the following:

```# Editors & Environment
.idea/
.vscode/
.vagrant/
.env
*.log```
